[package]
name = "picocom"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
color-eyre = "0.6.5"
ctrlc = "3.5.0"
dialoguer = "0.12.0"
notify = "8.2.0"
serialport = "4.7.3"

[profile.release]
codegen-units = 1
lto = true
